apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx
        ports:
        - containerPort: 80

# this file is used to scale the deployment to three pods
# (declerative way) using this configuration file to:
              # 1. Create a Deployment (kind: Deployment)
              # 2. Will place 3 replica Pods for this Deployment (replicas: 3)
              # 3. The Pods should run the hello-world image
